theme: jekyll-theme-minimal
# Minimal Mistakesを使う場合は remote_theme: "mmistakes/minimal-mistakes"
permalink: /:categories/:title/

# 基本情報の共通設定
title: "Ushi Log"
description: "サイト作成中です！"

owner_name: "ushidakyotaro"

# 数式 (KaTeX) を使う場合、kramdownの設定が必要なことがあります
kramdown:
  math_engine: katex

comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # 見た目のテーマ
    repository: "ushidakyotaro/ushidakyotaro.github.io" # あなたのリポジトリ名

plugins:
  - jekyll-seo-tag

show_drafts: false # trueだと_drafts/がすべての人に見えるようになる